### ISSUE TITLE
OSError: [Errno 5] EIO Task exception wasn't retrieved

### ISSUE THREAD

**Issue by JohnnyPicnic** [hugokernel/micropython-nanoweb#17]
Trying to run the example on a Pi PICO W and I can't get anything to load after the authentication.
This shows in the Thonny Shell:
```
Task exception wasn't retrieved
future: <Task> coro= <generator object 'handle' at 20031800>
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "nanoweb.py", line 166, in handle
  File "nanoweb.py", line 37, in send_file
  File "uasyncio/stream.py", line 1, in stream_awrite
  File "uasyncio/stream.py", line 1, in write
OSError: [Errno 5] EIO
```

If I restart and try ip:8001/ping I get the pong response

**Comment by hugokernel** [comment]
Which url are you trying to get the first time ?

Could you try to put all steps to reproduce the problem (and eventually, a simplified example with just the failing part).
